apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - www.30daysofazure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.30daysofazure.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer